
services:
  - type: web
    name: hw-store-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: <YOUR_MONGO_URI>
      - key: GOOGLE_CLIENT_ID
        value: <YOUR_GOOGLE_CLIENT_ID>
      - key: GOOGLE_CLIENT_SECRET
        value: <YOUR_GOOGLE_CLIENT_SECRET>
      - key: JWT_SECRET
        value: <YOUR_JWT_SECRET>
      - key: SESSION_SECRET
        value: <YOUR_SESSION_SECRET>
